
package ar.com.directv.test.spring.integration.async;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "OrdersPort", targetNamespace = "http://www.test.spring.integration.ws/orders")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface OrdersPort {


    /**
     * 
     * @param processOrderRequest
     * @return
     *     returns ar.com.directv.test.spring.integration.async.ProcessOrderResponse
     */
    @WebMethod
    @WebResult(name = "processOrderResponse", targetNamespace = "http://www.test.spring.integration.ws/orders", partName = "processOrderResponse")
    public ProcessOrderResponse processOrder(
        @WebParam(name = "processOrderRequest", targetNamespace = "http://www.test.spring.integration.ws/orders", partName = "processOrderRequest")
        ProcessOrderRequest processOrderRequest);

}
